# Numpy

- Based on Numerical 

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [4]:
arr.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [5]:
arr.reshape(4,3) # rows and column

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [6]:
arr.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

# array indexing:

In [11]:
arr=np.array([1,2,3,4])
arr[0]

1

In [8]:
arr[1]

2

In [9]:
arr.fill(5)

In [10]:
arr

array([5, 5, 5, 5])

In [13]:
arr=np.array([1,2,3,5])
arr1=np.array([6,7,8,9])

arr+arr1

array([ 7,  9, 11, 14])

In [16]:
arr.reshape(2,2)+arr1.reshape(2,2)

array([[ 7,  9],
       [11, 14]])

In [17]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [18]:
arr[0:1]

array([[1, 2, 3, 4, 5]])

In [22]:
arr[1:2] 

array([[ 6,  7,  8,  9, 10]])

In [24]:
# 3D 
f=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
f

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [25]:
f.ndim

3

In [33]:
f[0,0] # row and column

array([1, 2, 3])

In [34]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [35]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [36]:
arr.ndim

3

In [43]:
arr[0,0,1] # matrix, row, then index 

2

In [44]:
arr[0,0,0:] # matrix, row, then index

array([1, 2, 3])

In [49]:
arr[1,0:,0]

array([ 7, 10])

## 1D

In [54]:
## Array Dimension

a=np.array([1,2,3,4])
print("Shape: ",a.shape,"\nDimension",a.ndim)

Shape:  (4,) 
Dimension 1


# 2D 

In [56]:
b=np.array([[1,2,3,4],[5,6,7,8]])
print("Shape: ",b.shape,"\nDimension",b.ndim)

Shape:  (2, 4) 
Dimension 2


In [57]:
c=np.array([[12,13,14,15],[16,17,18,19],[19,20,21,23]])
print("Shape: ",c.shape,"\nDimension",c.ndim)

Shape:  (3, 4) 
Dimension 2


# 3rd  Dimension

In [58]:
d=np.array([[[14,15,16,17]],[[18,19,20,21]],[[22,23,24,25]]])
print("Shape: ",d.shape,"\nDimension",d.ndim)

Shape:  (3, 1, 4) 
Dimension 3


******

In [60]:
a=np.array(5) # minimum 1 col is required to make it 1D
print(a) # print a 
print(a.ndim) # dimension

5
0


In [62]:
a=np.random.rand(2,3)
print("Shape: ",a.shape,"\nDimension",a.ndim)

Shape:  (2, 3) 
Dimension 2


In [64]:
a=np.random.rand(2,3,2)
print("Shape: ",a.shape,"\nDimension",a.ndim)

Shape:  (2, 3, 2) 
Dimension 3


In [65]:
a

array([[[0.46626586, 0.89066885],
        [0.17645444, 0.98478683],
        [0.97461441, 0.11215467]],

       [[0.5645213 , 0.08359164],
        [0.64127181, 0.62183502],
        [0.08090973, 0.79773903]]])

In [67]:
a.reshape(3,4)

array([[0.46626586, 0.89066885, 0.17645444, 0.98478683],
       [0.97461441, 0.11215467, 0.5645213 , 0.08359164],
       [0.64127181, 0.62183502, 0.08090973, 0.79773903]])

In [68]:
np.random.rand(4,5)

array([[0.13194874, 0.41771454, 0.02186055, 0.91645776, 0.06487346],
       [0.16382824, 0.01215438, 0.28155086, 0.00739304, 0.81837473],
       [0.95709464, 0.01278603, 0.50428649, 0.70668182, 0.57697512],
       [0.03017909, 0.17612022, 0.77456294, 0.00244407, 0.59525057]])

In [70]:
np.random.randint(1,5) # genrate auto number between 1 to 5

2

In [71]:
np.random.rand(4,5)

array([[0.23468873, 0.29394372, 0.63986865, 0.66651302, 0.50129446],
       [0.90110081, 0.90739244, 0.52219977, 0.35085203, 0.92822973],
       [0.77337863, 0.80448341, 0.26010504, 0.18798214, 0.52304111],
       [0.60811029, 0.90718527, 0.39937236, 0.95339918, 0.49932821]])

## Slicing

In [1]:
import numpy as np

In [2]:
a=np.arange(0,12)
len(a)

12

In [3]:
f=a.reshape(3,4)
f

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
f.shape

(3, 4)

In [24]:
f.ndim

2

## 1D Array

In [4]:
g=np.ravel(f)
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
print(g.ndim)
print(g.size)

1
12


In [5]:
g[0:5] # start index:stop index

array([0, 1, 2, 3, 4])

In [6]:
g[4:7] # start index : stop index{EXCLUDED}

array([4, 5, 6])

In [7]:
g[:4]

array([0, 1, 2, 3])

## 2D Array

In [8]:
a2=np.array([[1,2,3,5],[6,7,8,9]])
a2

array([[1, 2, 3, 5],
       [6, 7, 8, 9]])

In [12]:
print("SHAPE :",a2.shape,"SIZE: ",a2.size)

SHAPE : (2, 4) SIZE:  8


In [27]:
print("Dimension :",a2.ndim)

Dimension : 2


In [17]:
print("",a2[0,1:4] )
print("\n",a2[1,1:4])

 [2 3 5]

 [7 8 9]


In [19]:
a2[0:2,2] # row 0 to 1: select 2nd element

array([3, 8])

In [20]:
a2[0:2,1:4] # row 0 to 1 : select 1 to 4 elements from row 1 to 4

array([[2, 3, 5],
       [7, 8, 9]])

## 3D Array

In [30]:
a3=np.array([[[1,2,3]],[[4,5,6]],[[7,8,9]]])

a3.ndim

3

In [33]:
# big 3 Dimension
a4=np.array([[[1,2,3],[4,5,6],[7,8,9]],
             [[10,11,12],[13,14,15],[16,17,18]],
            [[19,20,21],[22,23,24],[25,26,27]]])
a4.ndim

3

In [39]:
a4

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [40]:
print(a4[:3,1:4,:2]) #[matrix:row:column]


""" Select matrix, select row , select column"""

[[[ 4  5]
  [ 7  8]]

 [[13 14]
  [16 17]]

 [[22 23]
  [25 26]]]


' Select matrix, select row , select column'

In [41]:
a4.shape

(3, 3, 3)

In [42]:
a4.size

27

# View vs Copy
-------------------------

1. "COPY Array" : It will not affect the original copy,Any Changes made to the it will not be affected.
2. "VIEW Array" : Any Changes made to the view will affect the original Copy

In [59]:
arr=np.arange(0,4).reshape(1,4)
arr

array([[0, 1, 2, 3]])

### COPY METHOD

- It wont affect the Main Array

In [49]:
cop=np.copy(arr)
cop

array([[0, 1, 2, 3, 4]])

In [60]:
arr.ndim

2

In [63]:
copy=arr.copy()
copy[0,:1]=42

print(copy)
print(arr)

[[42  1  2  3]]
[[0 1 2 3]]


In [61]:
arr1=np.array([1,2,4,5,6,7])
arr1.ndim

1

In [64]:
copy1=arr1.copy()
copy1[0]=21

print(copy1)

[21  2  4  5  6  7]


#### VIEW will affect  the original Array

In [65]:
view=arr.view()
view[0,:1]=45

print(arr)
print(view)

[[45  1  2  3]]
[[45  1  2  3]]


### APPEND, INSERT, DELETE

In [1]:
import numpy as np

In [2]:
a=np.array([[1,2,3],
            [11,12,13]])
a
print(a.shape)
print(a.size)
print(a.ndim)

(2, 3)
6
2


### APPEND

In [3]:
# axis=0 is by rows

np.append(a,[[21,22,23]],axis=0)

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23]])

In [4]:
# Haven't udated any axis

np.append(a,[21,22,23])

array([ 1,  2,  3, 11, 12, 13, 21, 22, 23])

In [5]:
# Have updated axis 

np.append(a,[[5],[8]],axis=1) # by column

array([[ 1,  2,  3,  5],
       [11, 12, 13,  8]])

### INSERT

In [12]:
test=np.random.rand(3,4)
test

array([[0.59565425, 0.2043335 , 0.03544993, 0.68621794],
       [0.48869083, 0.00119823, 0.08346111, 0.30588635],
       [0.29982344, 0.77520821, 0.38913263, 0.32365988]])

In [24]:
g=test[0:3,1:3]
g

array([[0.2043335 , 0.03544993],
       [0.00119823, 0.08346111],
       [0.77520821, 0.38913263]])

In [27]:
g.ndim

2

In [28]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [33]:
np.insert(a,3,[4])

array([1, 2, 3, 4])

In [36]:
a1=np.arange(1,10).reshape(3,3)
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
np.insert(a1,2,[11,12,13],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [ 7,  8,  9]])

In [38]:
np.insert (a1,3,[11,12,13],axis=1)

array([[ 1,  2,  3, 11],
       [ 4,  5,  6, 12],
       [ 7,  8,  9, 13]])

In [39]:
np.insert(a1,3,[11,12,13])

array([ 1,  2,  3, 11, 12, 13,  4,  5,  6,  7,  8,  9])

### Delete Method

In [40]:
a3=np.arange(0,9).reshape(3,3)
a3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [41]:
np.delete(a3,0)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [42]:
np.delete(a3,1,axis=1) # axis=1 by column

array([[0, 2],
       [3, 5],
       [6, 8]])

In [43]:
np.delete(a3,0,axis=0) # axis=0 by rows

array([[3, 4, 5],
       [6, 7, 8]])

In [47]:
np.delete(a3,3) # index 3 got removed 

array([0, 1, 2, 4, 5, 6, 7, 8])

# Hstack and Vstack
----------------

1. Hstack to join Horizontally
2. Vstack to join Vertically

In [54]:
a=np.array([1,2,3])
b=np.array([4,5,6])


# Horizontally
result= np.hstack((a,b))
print(result)
print("Dimension: ",result.ndim)

[1 2 3 4 5 6]
Dimension:  1


In [55]:
# Performing Vstack
result=np.vstack((a,b))

print("Vertically")
print(result)
print("Dimension: ",result.ndim)

Vertically
[[1 2 3]
 [4 5 6]]
Dimension:  2


# Numpy Concatenation

In [56]:
arr1=np.array([[2,4],[6,8]])
arr1

array([[2, 4],
       [6, 8]])

In [57]:
arr2=np.array([[9,10],[11,12]])
arr2

array([[ 9, 10],
       [11, 12]])

In [59]:
np.concatenate((arr1,arr2),axis=0) # by rows

array([[ 2,  4],
       [ 6,  8],
       [ 9, 10],
       [11, 12]])

In [60]:
np.concatenate((arr1,arr2),axis=1) # by column

array([[ 2,  4,  9, 10],
       [ 6,  8, 11, 12]])